apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: dev
  name: dev
spec:
  ports:
  
    - protocol: TCP
      port: 1234
      targetPort: 1234
   
   
  selector:
    app: dev
  type: ClusterIP
