apiVersion: v1
kind: Service
metadata:
  namespace: unique
  labels:
    app: unique
  name: unique
spec:
  ports:
  
    - protocol: TCP
      port: 1234
      targetPort: 1234
   
   
  selector:
    app: unique
  type: ClusterIP
